name: LinksOnSigns
main: de.tobiyas.linksonsigns.LinksOnSigns
version: 1.9
website: http://dev.bukkit.org/server-mods/linksonsigns/
author: tobiyas
description: >
             sends link urls to persons clicking on the sign

commands:
  linksign:
    description: links a sign to an URL
    aliases: [lsign,lsigns,lsignns]
    usage: |
           /linksign <link-name> [URL]
  linksonsignsreload:
    description: reloading all urls in file
    aliases: [lsr]
    usage: |
           /linksonsignsreload
